#!/usr/bin/bash
if [ ! -S ~/.ssh/agent ]; then
  ssh-agent -a ~/.ssh/agent
  SSH_AUTH_SOCK=$HOME/.ssh/agent; export SSH_AUTH_SOCK;
  SSH_AGENT_PID=$(pidof ssh-agent); export SSH_AGENT_PID;
  ssh-add
else
  SSH_AUTH_SOCK=$HOME/.ssh/agent; export SSH_AUTH_SOCK;
  SSH_AGENT_PID=$(pidof ssh-agent); export SSH_AGENT_PID;
fi
